name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ] # 메인 브랜치에 push 될 때 실행
  pull_request:
    branches: [ main ] # 메인 브랜치에 pull request가 생성될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server via SSH
        run: |
          ssh -p 19058 -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use node
            
            cd /home/ubuntu/capstone-node-server
            git pull origin main
            npm install
            pm2 restart gateway
          EOF